### PR TITLE
hoverable nav

### LINKED ISSUE #112: bridge for brand redesign
**Note:** If you're a new contributor to this repository, refer to [CONTRIBUTING.md](https://github.com/GTBitsOfGood/bog-web/blob/master/CONTRIBUTING.md) before tackling this issue!

Describe the purpose of this enhancement in 1-2 sentences

make a dropdown toggle for roles page
more contentful models for some hard coded data
dynamic department count based on contentful length

## Action items
- list out the steps to make this issue a reality. use `code blocks` to explain specifics.

## Mockups
**[View on Figma for specifics on sizing variables](https://www.figma.com/file/aAThxeD86vXciqJRTmDLjyQG/BitsOfGood-web-redesign?node-id=3197%3A558)**

Include screenshots of appropriate mockups here, desktop and mobile views.

### PR DESCRIPTION
**Pull request by Fattimo**
Resolves #[112]

### CODE REVIEW

**Comment by Fattimo** [comment]
https://www.verkada.com/ follow this model

**Comment by Fattimo** [comment]
added a dropdown nav component

changed number of departments to be based on the number of departments loaded in

added a contentful property to current recruitment cycle so that the subheader is dynamic based on current active cycle

**Comment by Fattimo** [comment]
1 second need to add mobile view for new header

**Review by stephanie-he — DISMISSED** [review]
nice, thanks for making these changes!

**Pull request merged**
